# Generated by Django 5.0.6 on 2024-06-04 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Occupations',
            fields=[
                ('job_title', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('job_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=25)),
                ('email', models.EmailField(max_length=50)),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.occupations')),
            ],
        ),
    ]
